/// @description Insert description here
outline_init();
bossForThisItem = Boss.Lifesteal;
image_blend = c_white;
reset = false;
hover = false;
thisItemSelected = false;
bonusHealth = 0;
bonusSpeed = 0;
bonusDash = 0;
bonusDamage = 0;
bonusFirerate = 0;
bonusLifeSteal = 0;
bonusAura = 0;
bonusConjur = 0;
bonusCooldown = 0;
previewHealth = bonusHealth;
previewSpeed = bonusSpeed;
previewDash = bonusDash;
previewDamage = bonusDamage;
previewFirerate = bonusFirerate;
previewLifeSteal = bonusLifeSteal;
previewAura = bonusAura;
previewConjur = bonusConjur;
previewCooldown = bonusCooldown;